import Navbar from './Components/Navbar'
import Footer from './Pages/Footer/Footer'
import './globals.css'

export const metadata = {
  title: 'Design Agency',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar></Navbar>
        {children}
        <Footer></Footer>
      </body>
    </html>
  )
}
